---
sidebar: sidebar 
permalink: reference_kpls.html 
keywords: what's new, features, new, release notes, known, problems, limitations, application 
summary: SaaS Backup for Microsoft 365는 새로운 기능, 개선 사항 및 버그 수정을 제공하는 새로운 릴리즈를 정기적으로 소개합니다. 
---
= 알려진 문제 및 제한 사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음은 SaaS Backup for Microsoft 365의 애플리케이션 레벨에서 확인된 제한 사항입니다.



== SharePoint Online의 경우

SaaS Backup은 아카이빙된 SharePoint 사이트의 백업을 지원하지 않습니다.



== 비즈니스용 OneDrive

새로 추가된 드라이브는 서비스에 대한 동기화를 수동으로 완료할 때까지 감지되지 않습니다.



== Exchange Online의 경우

* SaaS Backup은 공용 폴더에 대한 백업을 지원하지 않습니다.
* * 고급 검색 * 은 Exchange Online에서만 사용할 수 있습니다. 이 설정은 기본적으로 비활성화되어 있습니다. 고객이 이 기능을 활성화하도록 요청해야 합니다. 고급 검색 사용 * 설정을 활성화한 후 관리자는 개별 사용자에 대해 검색 기능을 수동으로 활성화해야 합니다.




== 팀을 위해

* 채널 구성은 복원되지만 콘텐츠와 대화는 복원되지 않습니다.
* API 제한으로 인해 SaaS Backup은 SaaS Backup의 퍼블릭 채널과 프라이빗 채널을 구분할 수 없습니다.
* 높은 수준의 복원으로 대화가 아닌 사서함 및 SharePoint 데이터만 복원합니다.
* emojis 및 gifs에 대한 백업 또는 복원은 팀 채팅에서 지원되지 않습니다.
* 팀 채팅 대화 내보내기 전용 옵션은 HTML로 내보내기입니다. 대화에 게시된 첨부 파일 링크는 HTML 문서에 표시되지 않습니다.




== 을 클릭합니다

* 데이터를 내보낼 수 없습니다.
* 증분 백업 작업이 실패하고 'Partial Failure(부분 실패)'라는 오류 메시지가 나타날 수 있습니다. OneNote 섹션 몇 개를 백업하지 못했습니다.
* OneDrive 백업에는 .onebak 파일의 백업이 포함됩니다.
* 복구 통계를 다운로드할 수 없습니다.
* 데이터 내보내기 및 데이터 삭제는 지원되지 않습니다.




== 기타 문제 및 제한 사항

다음과 같은 알려진 문제와 제한 사항은 한 응용 프로그램에만 국한되지 않습니다.

Microsoft 365 서비스 계정에 등록하는 모든 사용자의 경우:

* SaaS Backup은 기본 인증만 지원합니다.


무료 평가판 사용자:

* 24시간 동안 서비스당 최대 10건의 복원이 허용됩니다.


라이센스가 있는 사용자의 경우:

* 24시간 동안 서비스당 최대 10개의 내보내기 데이터 복원이 허용됩니다. 다른 모든 복원 옵션에는 제한 사항이 없습니다.


사이트 모음 그룹을 복원하는 경우:

* 전체 사이트 모음 그룹이 삭제된 경우 컬렉션의 개인 그룹을 복원하지 못해 복원 작업 상태가 "부분적으로 실패함"으로 나타납니다. 이 경우 GUI에서 사이트에 액세스할 수 없습니다.


고급 검색 * 의 경우:

* 24시간 동안 최대 10개의 검색 작업이 허용됩니다.

